Controllers/QuartosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HOTEL360___Trabalho_final.Data;
using HOTEL360___Trabalho_final.Models;
using Microsoft.AspNetCore.Authorization;
using System.Drawing;

namespace HOTEL360___Trabalho_final.Controllers{

    [Authorize] // qualquer tarefa desta classe só pode ser efetuada por pessoas autorizadas (ie. autenticadas)
    public class QuartosController : Controller {

        /// <summary>
        /// referência à BD do projeto
        /// </summary>
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// objeto que contém os dados referentes ao ambiente 
        /// do Servidor
        /// </summary>
        private readonly IWebHostEnvironment _webHostEnvironment;

        public QuartosController(
         ApplicationDbContext context,
         IWebHostEnvironment webHostEnvironment) {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        /// <summary>
        /// mostra todos os quarto existentes na BD
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous] // esta anotação isenta da obrigação do utilizador estar autenticado
        // GET: Quartos
        public async Task<IActionResult> Index() {
            return View(await _context.Quartos.ToListAsync());
        }

        // GET: Quartos/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var quarto = await _context.Quartos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quarto == null) {
                return NotFound();
            }

            return View(quarto);
        }

        // GET: Quartos/Create
        /* apenas as pessoas autenticadas E que pertençam 
         * ao Role de GERENTE podem entrar */
        [Authorize(Roles = "Gerentes")]
        [HttpGet] // facultativo, pois esta função,
                  // por predefinição, já reage ao HTTP GET
        public IActionResult Create() {
            // a única ação desta função é mostrar a View quando quero iniciar a adição de um Quarto
            return View();
        }
        
        // POST: Quartos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Capacidade,Preco,PrecoAux,Descricao,Imagem, Localizacao")] Quartos quarto, IFormFile ImagemLogo) {

        /* Algoritmo
        * 1- há ficheiro?
        *    1.1 - não há ficheiro!
        *          devolver à view dizendo que o ficheiro
        *          é obrigatório
        *    1.2 - há ficheiro!
        *          Mas, é uma imagem (PNG, JPG)?
        *          1.2.1 - não é PNG nem JPG
        *                  devolver o controlo à View
        *                  e pedir PNG ou JPG
        *          1.2.2 - é uma imagem
        *                  - determinar o nome a atribuir 
        *                    ao ficheiro
        *                  - escrever esse nome na BD
        *                  - se a escrita na BD se concretizar
        *                    é que o ficheiro é guardado no 
        *                    disco rígido
        */

            // vars. auxiliares
            string nomeImagem = "";
            bool haImagem = false;

            // há ficheiro?
            if (ImagemLogo == null)
            {
                ModelState.AddModelError("",
                   "O fornecimento de uma Imagem é obrigatório!");
                return View(quarto);
            }
            else
            {
                // há ficheiro, mas é imagem?
                if (!(ImagemLogo.ContentType == "image/png" ||
                       ImagemLogo.ContentType == "image/jpeg")
                   )
                {
                    ModelState.AddModelError("",
                   "Tem de fornecer para a Imagem um ficheiro PNG ou JPG!");
                    return View(quarto);
                }
                else
                {
                    // há ficheiro, e é uma imagem válida
                    haImagem = true;
                    // obter o nome a atribuir à imagem
                    Guid g = Guid.NewGuid();
                    nomeImagem = g.ToString();
                    // obter a extensão do nome do ficheiro
                    string extensao = Path.GetExtension(ImagemLogo.FileName);
                    // adicionar a extensão ao nome da imagem
                    nomeImagem += extensao;
                    // adicionar o nome do ficheiro ao objeto que
                    // vem do browser
                    quarto.Imagem = nomeImagem;
                }
            }

            //avalia se os dados que chegam da View estão de acordo com o Model
            if (ModelState.IsValid) {
                                
                try
                {
                    //transferir o valor de PrecoAux para Preco
                    quarto.Preco = Convert.ToDecimal(quarto.PrecoAux.Replace('.', ','));

                    //adiciona os dados vindos da View à BD 
                    _context.Add(quarto);
                    //efetua COMMIT na BD
                    await _context.SaveChangesAsync();

                    // se há ficheiro de imagem,
                    // vamos guardar no disco rígido do servidor
                    if (haImagem)
                    {
                        // determinar onde se vai guardar a imagem
                        string nomePastaOndeGuardarImagem =
                           _webHostEnvironment.WebRootPath;
                        // já sei o caminho até à pasta wwwroot
                        // especifico onde vou guardar a imagem
                        nomePastaOndeGuardarImagem =
                           Path.Combine(nomePastaOndeGuardarImagem, "Imagens");
                        // e, existe a pasta 'Imagens'?
                        if (!Directory.Exists(nomePastaOndeGuardarImagem))
                        {
                            Directory.CreateDirectory(nomePastaOndeGuardarImagem);
                        }
                        // juntar o nome do ficheiro à sua localização
                        string nomeFinalDaImagem =
                           Path.Combine(nomePastaOndeGuardarImagem, nomeImagem);

                        // guardar a imagem no disco rigído
                        using var stream = new FileStream(
                           nomeFinalDaImagem, FileMode.Create
                           );
                        await ImagemLogo.CopyToAsync(stream);
                    }

                    //redireciona o utilizador para a página Index 
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // se cheguei aqui é pq aconteceu um problema
                    // crítico. TEM de ser tratado.
                    //    - devolver o controlo ao utilizador
                    //    - corrigir o erro
                    //    - escrever os dados do erro num LOG
                    //    - escrever os dados do erro numa tabela da BD
                    //    - etc.
                    throw;
                }         

            
            }

            //se chegou aqui é porque algo não correu bem
            //volta à View com os dados fornecidos pela View 
            return View(quarto);
        }

        /* apenas as pessoas autenticadas E que pertençam 
         * ao Role de GERENTES podem entrar */
        [Authorize(Roles = "Gerentes")]
        // GET: Quartos/Edit/5
        public async Task<IActionResult> Edit(int? id)  {
            if (id == null) {
                return NotFound();
            }

            var quarto = await _context.Quartos.FindAsync(id);
            if (quarto == null) {
                return NotFound();
            }

            // Preencher o valor de PrecoAux para exibição
            quarto.PrecoAux = quarto.Preco.ToString();

            string nomeImagem = quarto.Imagem;

            return View(quarto);
        }
                
        // POST: Quartos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Capacidade,Preco,PrecoAux,Descricao,Imagem, Localizacao")] Quartos quarto, IFormFile ImagemLogo) {
            if (id != quarto.Id)  {
                return NotFound();
            }            

            //avalia se os dados que chegam da View estão de acordo com o Model
            if (ModelState.IsValid) {
                try {
                    if (ImagemLogo != null && (ImagemLogo.ContentType == "image/png" || ImagemLogo.ContentType == "image/jpeg"))
                    {
                        // Obter o nome a atribuir à imagem
                        Guid g = Guid.NewGuid();
                        string nomeImagem = g.ToString();
                        // Obter a extensão do nome da imagem
                        string extensao = Path.GetExtension(ImagemLogo.FileName);
                        nomeImagem += extensao;

                        // Define o caminho para guardar a imagem
                        string nomePastaOndeGuardarImagem = Path.Combine(_webHostEnvironment.WebRootPath, "Imagens");
                        if (!Directory.Exists(nomePastaOndeGuardarImagem))
                        {

Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HOTEL360___Trabalho_final.Data;
using HOTEL360___Trabalho_final.Models;
using Microsoft.AspNetCore.Authorization;

namespace HOTEL360___Trabalho_final.Controllers {

    [Authorize] // qualquer tarefa desta classe só pode ser efetuada por pessoas autorizadas (ie. autenticadas)
    public class ServicosController : Controller {

        /// <summary>
        /// referência à BD do projeto
        /// </summary>
        private readonly ApplicationDbContext _context;

        public ServicosController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// mostra todos os serviços existentes na BD
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous] // esta anotação isenta da obrigação do utilizador estar autenticado
        // GET: Servicos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Servicos.ToListAsync());
        }

        // GET: Servicos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servicos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servico == null)
            {
                return NotFound();
            }

            return View(servico);
        }

        // GET: Servicos/Create
        /* apenas as pessoas autenticadas E que pertençam 
         * ao Role de GERENTE podem entrar */
        [Authorize(Roles = "Gerentes")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servicos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao,PrecoAux,Preco")] Servicos servico)
        {
            if (ModelState.IsValid) {

                try {               
                
                    //transferir o valor de PrecoAux para Preco
                    servico.Preco = Convert.ToDecimal(servico.PrecoAux.Replace('.', ','));

                    //adiciona os dados vindos da View à BD
                    _context.Add(servico);
                    //efetua COMMIT na BD
                    await _context.SaveChangesAsync();
                    //redireciona o utilizador para a página Index
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    
                    // se cheguei aqui é pq aconteceu um problema
                    // crítico. TEM de ser tratado.
                    //    - devolver o controlo ao utilizador
                    //    - corrigir o erro
                    //    - escrever os dados do erro num LOG
                    //    - escrever os dados do erro numa tabela da BD
                    //    - etc.
                    throw;                    


                }
                
            }
            //se chegou aqui é porque algo não correu bem
            //volta à View com os dados fornecidos pela View 
            return View(servico);
        }

        /* apenas as pessoas autenticadas E que pertençam 
         * ao Role de GERENTE podem entrar */
        [Authorize(Roles = "Gerentes")]
        // GET: Servicos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servicos.FindAsync(id);
            if (servico == null)
            {
                return NotFound();
            }

            // Preencher o valor de PrecoAux para exibição
            servico.PrecoAux = servico.Preco.ToString();

            return View(servico);
        }

        // POST: Servicos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao,Preco, PrecoAux")] Servicos servico)
        {
            if (id != servico.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //transferir o valor de PrecoAux para Preco
                    servico.Preco = Convert.ToDecimal(servico.PrecoAux.Replace('.', ','));

                    _context.Update(servico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicosExists(servico.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servico);
        }

        /* apenas as pessoas autenticadas E que pertençam 
         * ao Role de GERENTE podem entrar */
        [Authorize(Roles = "Gerentes")]
        // GET: Servicos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servicos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servico == null)
            {
                return NotFound();
            }

            return View(servico);
        }

        // POST: Servicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var servico = await _context.Servicos.FindAsync(id);
            if (servico != null)
            {
                _context.Servicos.Remove(servico);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicosExists(int id)
        {
            return _context.Servicos.Any(e => e.Id == id);
        }
    }
}

Views/Reservas/Delete.cshtml
@model HOTEL360___Trabalho_final.Models.Reservas

@{
    ViewData["Title"] = "Apagar Reserva";
}

<br />
<h1 style="color: #fff;">Apagar Reserva</h1>
<h3 style="color: #fff;">Tem a certeza que pretende eliminar este reserva?</h3>


<div class="row mb-4">
    <div class="col-md-4">
        <div class="card">
            <div class="row no-gutters">
                <div class="col-md-12">
                    <div class="card-body"> 
                        <dl class="row">
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.DataReserva)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.DataReserva)
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.DataCheckIN)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.DataCheckIN)
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.DataCheckOUT)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.DataCheckOUT)
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.Quarto)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.Quarto.Nome)
                            </dd>
                            @* lista dos Serviços da Reserva *@
                            <dt class="col-sm-6">
                                Serviços
                            </dt>
                            <dd class="col-sm-6">
                                <ul>
                                    @foreach (var serv in Model.ListaServicos)
                                    {
                                        <li>
                                            <a asp-action="Details"
                                               asp-controller="Servicos"
                                               asp-route-id="@serv.Id">@serv.Nome</a>
                                        </li>
                                    }
                                </ul>
                            </dd>
                            <dt class="col-sm-6">
                                Hospede
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.Hospede.Nome)
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.ValorPago)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.ValorPago)€
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.ValorTotal)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.ValorTotal)€
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.ValorAPagar)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.ValorAPagar)€
                            </dd>
                        </dl>
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Apagar" class="btn btn-danger" />
                            <a class="btn btn-secondary" asp-action="Index">Regressar à listagem de Reservas</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Reservas/Details.cshtml
@model HOTEL360___Trabalho_final.Models.Reservas

@{
    ViewData["Title"] = "Detalhes da Reserva";
}

<br />
<h1 style="color: #fff;">Detalhes da Reserva</h1>
<br />

<div class="row mb-4">
    <div class="col-md-8">
        <div class="card">
            <div class="row no-gutters">
                <div class="col-md-6">
                    <div class="card-body">
                        <h3 class="card-title">Data da reserva: @Model.DataReserva.ToString("dd/MM/yyyy HH:mm")</h3>
                        <br />
                        <dl class="row">
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.DataCheckIN)
                            </dt>
                            <dd class="col-sm-6">
                                @Model.DataCheckIN.ToString("dd/MM/yyyy HH:mm")
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.DataCheckOUT)
                            </dt>
                            <dd class="col-sm-6">
                                @Model.DataCheckOUT.ToString("dd/MM/yyyy HH:mm")
                            </dd>                          
                            @* Mostra o nome do quarto associado à Reserva *@
                            <dt class="col-sm-6">
                                Quarto
                            </dt>
                            <dd class="col-sm-6">
                                <a asp-action="Details"
                                   asp-controller="Quartos"
                                   asp-route-id="@Model.QuartoFK">
                                    @Html.DisplayFor(model => model.Quarto.Nome)
                                </a>                              
                            </dd>
                            @* lista dos Serviços da Reserva *@
                            <dt class="col-sm-6">
                                Serviços
                            </dt>
                            <dd class="col-sm-6">
                                <ul>
                                    @foreach (var serv in Model.ListaServicos)
                                    {
                                        <li>
                                            <a asp-action="Details"
                                               asp-controller="Servicos"
                                               asp-route-id="@serv.Id">@serv.Nome</a>
                                        </li>
                                    }
                                </ul>
                            </dd>                           
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.ValorTotal)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.ValorTotal)€
                            </dd>
                            <dt class="col-sm-6">
                                @Html.DisplayNameFor(model => model.ValorPago)
                            </dt>
                            <dd class="col-sm-6">
                                @Html.DisplayFor(model => model.ValorPago)€
                            </dd>
                            <dt class="col-sm-6 valor-a-pagar">
                                @Html.DisplayNameFor(model => model.ValorAPagar)
                            </dt>
                            <dd class="col-sm-6 valor-a-pagar">
                                @Html.DisplayFor(model => model.ValorAPagar)€
                            </dd>
                            @if (User.IsInRole("Gerentes") || User.IsInRole("Reccecionistas"))
                            {
                                <dt class="col-sm-6">
                                    Hospede
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.Hospede.Nome)
                                </dd>
                            }

                        </dl>

                        <br />
                        <div class="mt-3">
                            @if (User.IsInRole("Gerentes") || User.IsInRole("Reccecionistas"))
                            {
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
                            }
                            <a class="btn btn-secondary" asp-action="Index">Regressar à listagem de Reservas</a>
                            
                        </div>
                    </div>
                </div>
                <div class="col-md-6">                    
                    <img src="~/Imagens/@Model.Quarto.Imagem"
                         alt="Imagem do quarto @Model.Quarto.Nome"
                         title="@Model.Quarto.Nome"
                         class="card-img" />
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .card-img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .valor-a-pagar {
        color: red; /* Cor do texto vermelho */
    }
</style>

Views/Reservas/Index.cshtml
@model IEnumerable<HOTEL360___Trabalho_final.Models.Reservas>

@{
    ViewData["Title"] = "Reservas";
}

<br />
<h1 style="color: #ffffff;">Lista de Reservas</h1>

<h4>
    <button class="btn-create" onclick="window.location.href='@Url.Action("Create")'">Nova Reserva</button>
</h4>
<br />

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    @if (User.IsInRole("Gerentes") || User.IsInRole("Reccecionistas"))
                    {
                        <h1 class="card-title">Reserva de: @Html.DisplayFor(model => item.Hospede.Nome)</h1>
                        <hr />
                        <p class="card-text"><strong>@Html.DisplayNameFor(model => model.DataReserva): </strong>@Html.DisplayFor(modelItem => item.DataReserva)</p>
                    } else
                    {
                        <h1 class="card-title">Data da reserva: @Html.DisplayFor(modelItem => item.DataReserva)</h1>
                        <br />
                    }                    
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.DataCheckIN): </strong>@Html.DisplayFor(modelItem => item.DataCheckIN)</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.DataCheckOUT): </strong>@Html.DisplayFor(modelItem => item.DataCheckOUT)</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.Quarto): </strong>@Html.DisplayFor(modelItem => item.Quarto.Nome)</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.ValorTotal): </strong>@Html.DisplayFor(modelItem => item.ValorTotal)€</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.ValorPago): </strong>@Html.DisplayFor(modelItem => item.ValorPago)€</p>
                    <p class="card-text valor-a-pagar"><strong>@Html.DisplayNameFor(model => model.ValorAPagar): </strong>@Html.DisplayFor(modelItem => item.ValorAPagar)€</p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <p>
                            @if (User.IsInRole("Gerentes") || User.IsInRole("Reccecionistas"))
                            {
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                            }

                            <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                            @if (User.IsInRole("Gerentes") || User.IsInRole("Reccecionistas"))
                            {
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
                            }
                        </p>
                    }
                </div>
            </div>
        </div>
    }
</div>

<style>
    /* Estilos para o botão */
    .btn-create {
        background-color: #e78d3c; /* Cor de fundo laranja, pode ser ajustada conforme necessário */
        color: #fff; /* Cor do texto branco */
        border: none; /* Remove a borda padrão */
        padding: 10px 20px; /* Espaçamento interno */
        font-size: 18px; /* Tamanho da fonte */
        cursor: pointer; /* Mostra um cursor ao passar o mouse */
        border-radius: 5px; /* Borda arredondada */
        transition: background-color 0.3s ease; /* Efeito de transição suave */
    }

        /* Hover (quando o mouse passa por cima) */
        .btn-create:hover {
            background-color: #e06f09; /* Cor de fundo mais escura ao passar o mouse */
        }

        .valor-a-pagar{
            color: red; /* Cor do texto vermelho */
        }

</style>